name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_827352416 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
      - name: 'Qodana Configuración personalizada'
        run: |
          echo 'version: "1.0"
          profile:
            name: "qodana.recommended"
          exclude:
            - name: "RedundantGetter"
          licenseAudit:
            allowedLicenses:
              - Apache-2.0
              - MIT
              - BSD-3-Clause
              - EPL-1.0
              - LGPL-2.0-or-later
              - LGPL-2.1-only
              - GPL-2.0-only
              - BSD-3-CLAUSE-NO-TRADEMARK' > qodana.yaml
